name: CI

on:
  pull_request:
    types: [labeled]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read file
        id: read-file
        run: |
          const fs = require('fs');
          const fileContents = fs.readFileSync('./file.txt', 'utf8');
          console.log(fileContents);
          console.log(`::set-output name=fileContents::${fileContents}`)
      
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **File Contents:** ${{ steps.read-file.outputs.fileContents }}

          
