name: CI

on:
  pull_request:
    types: [labeled]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Read file
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const fileContents = fs.readFileSync('file.txt', 'utf8');
            console.log(fileContents);
            core.setOutput('fileContents', fileContents);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Hello MAIN**
            File contents: ${{ steps.readfile.outputs.fileContents }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          
