name: CI

on:
  pull_request:
    types: [labeled]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Read file
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "file.txt"
          
      - name: Echo file txt
        run: echo "${{ steps.read_file.outputs.contents }}"
        
      - name: Post comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TEST_GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `File contents:\n\n${{ steps.read_file.outputs.contents }}`
            });
       
#      - name: Add PR comment
#        uses: mshick/add-pr-comment@v2
#        with:
#          message: |
#            **File Contents:** ${{ steps.read-file.outputs.fileContents }}
#          message-id: add-pr-comment
#          repo-token: ${{ secrets.TEST_GITHUB_TOKEN }}
#          allow-repeats: false
#          status: success
#          issue-number: ${{ github.event.pull_request.number }}

          
